%{ // Start C declarations block for Bison.
#include <stdio.h> // Include standard IO declarations.
#include <stdlib.h> // Include utility declarations.
#include <string.h> // Include string helper declarations.
#include "ast.h" // Include AST node definitions.

extern int yylex(void); // Declare lexer function generated by Flex.
extern int yylineno; // Declare current lexer line counter.
extern FILE *yyin; // Declare lexer input file stream.

MiniAstNode *miniRoot = NULL; // Store final parsed program root.

void yyerror(const char *msg); // Forward declare syntax error reporter.
%} // End C declarations block.

%code requires { // Start declarations copied to parser header.
#include "ast.h" // Expose AST types to lexer via parser.tab.h.
} // End header declarations block.

%union { // Start semantic value union definition.
    MiniAstNode *node; // Store AST pointer values.
    char *text; // Store identifier text values.
    int number; // Store integer literal values.
    MiniDataType dtype; // Store parsed type values.
} // End semantic value union.

%token <text> ID // Declare identifier token with text payload.
%token <number> NUMBER // Declare integer literal token.
%token INT BOOL IF ELSE WHILE PRINT TRUE FALSE // Declare keyword tokens.
%token ASSIGN PLUS MINUS MUL DIV LT GT EQ NE // Declare operator tokens.
%token LP RP LB RB SEMI COMMA // Declare delimiter tokens.

%type <node> program stmt_list stmt block declaration assignment if_stmt while_stmt print_stmt expr id_list // Declare non-terminal AST types.
%type <dtype> type_spec // Declare non-terminal type payload.

%right ASSIGN // Set assignment precedence lowest and right-associative.
%left EQ NE // Set equality operator precedence.
%left LT GT // Set relational operator precedence.
%left PLUS MINUS // Set additive operator precedence.
%left MUL DIV // Set multiplicative operator precedence.
%nonassoc LOWER_THAN_ELSE // Resolve dangling else precedence helper.
%nonassoc ELSE // Make else bind to nearest if.

%% // Start grammar rules section.

program // Define program root rule.
    : stmt_list { // Match top-level statement list.
        MiniAstNode *CSECU = createNode(NODE_PROGRAM, yylineno); // Create program AST root.
        CSECU->left = $1; // Attach top-level statements list.
        miniRoot = CSECU; // Save root for main driver.
        $$ = CSECU; // Return program root node.
      } // End program action.
    ; // End program rule.

stmt_list // Define recursive statement list rule.
    : stmt_list stmt { $$ = appendNode($1, $2); } // Append new statement to existing list.
    | stmt { $$ = $1; } // Base case with single statement.
    ; // End statement list rule.

stmt // Define all possible statements.
    : declaration { $$ = $1; } // Map declaration statement.
    | assignment { $$ = $1; } // Map assignment statement.
    | if_stmt { $$ = $1; } // Map if statement.
    | while_stmt { $$ = $1; } // Map while statement.
    | print_stmt { $$ = $1; } // Map print statement.
    | block { $$ = $1; } // Map block statement.
    ; // End statement rule.

block // Define scoped block rule.
    : LB stmt_list RB { // Match braces around statement list.
        MiniAstNode *Tanjim = createNode(NODE_BLOCK, yylineno); // Create block node.
        Tanjim->left = $2; // Attach block statement list.
        $$ = Tanjim; // Return block node.
      } // End non-empty block action.
    | LB RB { // Match empty braces block.
        MiniAstNode *Tanjim = createNode(NODE_BLOCK, yylineno); // Create block node.
        Tanjim->left = NULL; // Keep block body empty.
        $$ = Tanjim; // Return empty block node.
      } // End empty block action.
    ; // End block rule.

type_spec // Define declaration type keywords.
    : INT { $$ = TYPE_INT; } // Map int keyword to integer type.
    | BOOL { $$ = TYPE_BOOL; } // Map bool keyword to boolean type.
    ; // End type rule.

id_list // Define comma-separated identifier list.
    : id_list COMMA ID { // Extend identifier list with one more name.
        MiniAstNode *Jami = createIdentifierNode($3, yylineno); // Create identifier node for current name.
        $$ = appendNode($1, Jami); // Append identifier node to list.
        free($3); // Free lexer-allocated identifier text.
      } // End recursive id list action.
    | ID { // Base identifier list case.
        $$ = createIdentifierNode($1, yylineno); // Create identifier node as list head.
        free($1); // Free lexer-allocated identifier text.
      } // End base id list action.
    ; // End id_list rule.

declaration // Define declaration statement rule.
    : type_spec id_list SEMI { // Match typed variable declaration list.
        MiniAstNode *declList = NULL; // Prepare declaration list head.
        MiniAstNode *Risbee = $2; // Start iterating identifier nodes.
        while (Risbee != NULL) { // Convert each identifier into declaration node.
            MiniAstNode *oneDecl = createNode(NODE_DECL, Risbee->lineNumber); // Create declaration AST node.
            oneDecl->textValue = strdup(Risbee->textValue); // Copy variable name into declaration node.
            oneDecl->dataType = $1; // Store declaration type info.
            declList = appendNode(declList, oneDecl); // Append declaration to resulting list.
            Risbee = Risbee->next; // Move to next identifier node.
        } // End identifier conversion loop.
        freeAST($2); // Free temporary identifier chain nodes.
        $$ = declList; // Return declaration node list.
      } // End declaration action.
    ; // End declaration rule.

assignment // Define assignment statement rule.
    : ID ASSIGN expr SEMI { // Match assignment syntax.
        MiniAstNode *Monir = createNode(NODE_ASSIGN, yylineno); // Create assignment node.
        Monir->textValue = strdup($1); // Save assignment target variable name.
        Monir->left = $3; // Attach right-hand expression subtree.
        $$ = Monir; // Return assignment node.
        free($1); // Free lexer-allocated identifier string.
      } // End assignment action.
    ; // End assignment rule.

if_stmt // Define if and if-else statement rules.
    : IF LP expr RP stmt %prec LOWER_THAN_ELSE { // Match if without else part.
        MiniAstNode *MyScan = createNode(NODE_IF, yylineno); // Create if node.
        MyScan->left = $3; // Attach condition expression.
        if ($5->nodeKind == NODE_BLOCK) { MyScan->right = $5; } // Reuse block node directly.
        else { MiniAstNode *wrap = createNode(NODE_BLOCK, $5->lineNumber); wrap->left = $5; MyScan->right = wrap; } // Wrap single statement into block.
        MyScan->third = NULL; // Keep else branch empty.
        $$ = MyScan; // Return if node.
      } // End if-without-else action.
    | IF LP expr RP stmt ELSE stmt { // Match if statement with else part.
        MiniAstNode *MyScan = createNode(NODE_IF, yylineno); // Create if node.
        MyScan->left = $3; // Attach condition expression.
        if ($5->nodeKind == NODE_BLOCK) { MyScan->right = $5; } // Reuse then block when already block.
        else { MiniAstNode *wrapThen = createNode(NODE_BLOCK, $5->lineNumber); wrapThen->left = $5; MyScan->right = wrapThen; } // Wrap then statement.
        if ($7->nodeKind == NODE_BLOCK) { MyScan->third = $7; } // Reuse else block when already block.
        else { MiniAstNode *wrapElse = createNode(NODE_BLOCK, $7->lineNumber); wrapElse->left = $7; MyScan->third = wrapElse; } // Wrap else statement.
        $$ = MyScan; // Return if-else node.
      } // End if-with-else action.
    ; // End if_stmt rule.

while_stmt // Define while loop rule.
    : WHILE LP expr RP stmt { // Match while syntax.
        MiniAstNode *Sara = createNode(NODE_WHILE, yylineno); // Create while node.
        Sara->left = $3; // Attach loop condition expression.
        if ($5->nodeKind == NODE_BLOCK) { Sara->right = $5; } // Reuse body block when present.
        else { MiniAstNode *wrap = createNode(NODE_BLOCK, $5->lineNumber); wrap->left = $5; Sara->right = wrap; } // Wrap single body statement.
        $$ = Sara; // Return while node.
      } // End while action.
    ; // End while_stmt rule.

print_stmt // Define print statement rule.
    : PRINT LP expr RP SEMI { // Match print(expression) statement.
        MiniAstNode *Ans = createNode(NODE_PRINT, yylineno); // Create print node.
        Ans->left = $3; // Attach printed expression.
        $$ = Ans; // Return print node.
      } // End print action.
    ; // End print_stmt rule.

expr // Define expression grammar with precedence.
    : expr PLUS expr { $$ = createBinaryNode("+", $1, $3, yylineno); } // Build addition node.
    | expr MINUS expr { $$ = createBinaryNode("-", $1, $3, yylineno); } // Build subtraction node.
    | expr MUL expr { $$ = createBinaryNode("*", $1, $3, yylineno); } // Build multiplication node.
    | expr DIV expr { $$ = createBinaryNode("/", $1, $3, yylineno); } // Build division node.
    | expr LT expr { $$ = createBinaryNode("<", $1, $3, yylineno); } // Build less-than node.
    | expr GT expr { $$ = createBinaryNode(">", $1, $3, yylineno); } // Build greater-than node.
    | expr EQ expr { $$ = createBinaryNode("==", $1, $3, yylineno); } // Build equality node.
    | expr NE expr { $$ = createBinaryNode("!=", $1, $3, yylineno); } // Build inequality node.
    | LP expr RP { $$ = $2; } // Return grouped expression.
    | NUMBER { $$ = createNumberNode($1, yylineno); } // Build number literal node.
    | TRUE { $$ = createBoolNode(1, yylineno); } // Build true boolean literal node.
    | FALSE { $$ = createBoolNode(0, yylineno); } // Build false boolean literal node.
    | ID { $$ = createIdentifierNode($1, yylineno); free($1); } // Build identifier reference node.
    ; // End expression rule.

%% // End grammar rules section.

void yyerror(const char *msg) { // Define human-readable syntax error printer.
    fprintf(stderr, "Syntax Error (line %d): %s\n", yylineno, msg); // Print line-aware syntax error.
} // End syntax error function.
